1. Import the NumPy library and assign to the alias np.
2. Use the numpy.genfromtxt() function to read the nyc_taxis.csv file into NumPy. Assign the result to taxi.
3. Use the ndarray.shape attribute to assign the shape of taxi to taxi_shape.


In [8]:
import numpy as np

In [9]:
taxi = np.genfromtxt('nyc_taxis.csv', delimiter = ',')

In [10]:
taxi_shape = taxi.shape
taxi_shape

(89561, 15)

1. Use the numpy.genfromtxt() function to again read the nyc_taxis.csv file into NumPy, but this time, skip the first row. Assign the result to taxi.
2. Assign the shape of taxi to taxi_shape.


In [11]:
taxi = taxi[1:]

In [12]:
taxi_shape = taxi.shape
taxi_shape

(89560, 15)

Use vectorized boolean operations to:
1. Evaluate whether the elements in array a are less than 3. Assign the result to a_bool.
2. Evaluate whether the elements in array b are equal to "blue". Assign the result to b_bool.
3. Evaluate whether the elements in array c are greater than 100. Assign the result to c_bool.
4. Once you've run your code, use the variable inspector below the code box to view each boolean array.


In [18]:
a = np.array([1,2,3,4,5])
b = np.array(['blue','blue','red','blue'])
c = np.array([80.0, 103.0, 96.9, 200.3])

In [19]:
a_bool = a < 3
b_bool = b == 'blue'
c_bool= c > 100

In [20]:
print(a_bool)
print(b_bool)
print(c_bool)

[ True  True False False False]
[ True  True False  True]
[False  True False  True]


### Boolean Indexing with 1D ndarrays

In [21]:
pickup_month = taxi[:,1]
january_bool = pickup_month == 1

In [23]:
january = pickup_month[january_bool]

In [24]:
january_rides = january.shape[0]
print(january_rides)

13481


Calculate the number of rides in the taxi ndarray that are from February:
1. Create a boolean array, february_bool, that evaluates whether the items in pickup_month are equal to 2.
2. Use the february_bool boolean array to index pickup_month. Assign the result to february.
3. Use the ndarray.shape attribute to find the number of items in february. Assign the result to february_rides.
4. Once you have run your code, use the variable inspector to view the number of rides for February


In [25]:
pickup_month = taxi[:,1]
february_bool = pickup_month == 2

In [27]:
february = pickup_month[february_bool]

In [28]:
february_rides = february.shape[0]
print(february_rides)

13333


 ### Boolean Indexing with 2D ndarrays

In [90]:
trip_mph = taxi[:,7]/(taxi[:,8]/3600)

In [32]:
trip_mph_bool = trip_mph > 20000
trip_over_20000_mph = taxi[trip_mph_bool,5:9]

In [33]:
print(trip_over_20000_mph)

[[ 2.   2.  23.   1. ]
 [ 2.   2.  19.6  1. ]
 [ 2.   2.  16.7  2. ]
 [ 3.   3.  17.8  2. ]
 [ 2.   2.  17.2  2. ]
 [ 3.   3.  16.9  3. ]
 [ 2.   2.  27.1  4. ]]


1. Create a boolean array, tip_bool, that determines which rows have values for the tip_amount column of more than 50.

2. Use the tip_bool array to select all rows from taxi with values tip amounts of more than 50, and the columns from indexes 5 to 13 inclusive. Assign the resulting array to top_tips


In [34]:
tip_amount = taxi[:,12]
tip_bool = tip_amount > 50
top_tips = taxi[tip_bool,5:14]

### Assigning Values in ndarray

In [62]:
taxi_modified = taxi.copy()

In [63]:
ones = np.array([[1,1,1,1],
                 [1,1,1,1],
                 [1,1,1,1]])

In [64]:
ones[1,2] = 99

In [65]:
print(ones)

[[ 1  1  1  1]
 [ 1  1 99  1]
 [ 1  1  1  1]]


In [66]:
ones[0] = 44
print(ones)

[[44 44 44 44]
 [ 1  1 99  1]
 [ 1  1  1  1]]


In [67]:
ones[:,2] = 0
print(ones)

[[44 44  0 44]
 [ 1  1  0  1]
 [ 1  1  0  1]]


In [68]:
taxi_modified[0][0]

2016.0

To help you practice without making changes to our original array, we have used the ndarray.copy() method to make taxi_modified, a copy of our original for these exercises.

1. The value at column index 5 (pickup_location) of row index 28214 is incorrect. Use assignment to change this value to 1 in the taxi_modified ndarray.
2. The first column (index 0) contains year values as four digit numbers in the format YYYY (2016, since all trips in our data set are from 2016). Use assignment to change these values to the YY format (16) in the taxi_modified ndarray.
3. The values at column index 7 (trip_distance) of rows index 1800 and 1801 are incorrect. Use assignment to change these values in the taxi_modified ndarray to the mean value for that column.


In [69]:
taxi_modified[28214,5] = 1
taxi_modified[:,0] = 16
taxi_modified[1800:1802,7] = taxi_modified[:,7].mean()

### Assignment Using Boolean Arrays

We again used the ndarray.copy() method to make taxi_copy, a copy of our original for this exercise.

1. Select the fourteenth column (index 13) in taxi_copy. Assign it to a variable named total_amount.
2. For rows where the value of total_amount is less than 0, use assignment to change the value to 0.

In [70]:
a2 = np.array([1,2,3,4,5])
a2_bool = a2 > 2
a2[a2_bool] = 99
print(a2)

[ 1  2 99 99 99]


In [71]:
total_amount = taxi_modified[13] 
total_amount[total_amount < 0] = 0

In [72]:
b = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

In [74]:
b[b > 4] = 99
b

array([[ 1,  2,  3],
       [ 4, 99, 99],
       [99, 99, 99]])

In [75]:
c = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

In [76]:
c[c[:,1]>2,1] = 99

In [77]:
c

array([[ 1,  2,  3],
       [ 4, 99,  6],
       [ 7, 99,  9]])

In [79]:
zeros = np.zeros([taxi.shape[0],1])
taxi_modified = np.concatenate([taxi,zeros], axis = 1)
print(taxi_modified)

[[2.016e+03 1.000e+00 1.000e+00 ... 6.999e+01 1.000e+00 0.000e+00]
 [2.016e+03 1.000e+00 1.000e+00 ... 5.430e+01 1.000e+00 0.000e+00]
 [2.016e+03 1.000e+00 1.000e+00 ... 3.780e+01 2.000e+00 0.000e+00]
 ...
 [2.016e+03 6.000e+00 3.000e+01 ... 6.334e+01 1.000e+00 0.000e+00]
 [2.016e+03 6.000e+00 3.000e+01 ... 4.475e+01 1.000e+00 0.000e+00]
 [2.016e+03 6.000e+00 3.000e+01 ... 5.484e+01 2.000e+00 0.000e+00]]


We have created a new copy of our taxi dataset, taxi_modified with an additional column containing the value 0 for every row.

1. In our new column at index 15, assign the value 1 if the pickup_location_code (column index 5) corresponds to an airport location, leaving the value as 0 otherwise by performing these three operations:
2. For rows where the value for the column index 5 is equal to 2 (JFK Airport), assign the value 1 to column index 15.
3. For rows where the value for the column index 5 is equal to 3 (LaGuardia Airport), assign the value 1 to column index 15.
4. For rows where the value for the column index 5 is equal to 5 (Newark Airport), assign the value 1 to column index 15.


In [80]:
taxi_modified[taxi_modified[:,5] == 2,15] = 1

In [81]:
taxi_modified[taxi_modified[:,5] == 3,15] = 1
taxi_modified[taxi_modified[:,5] == 5,15] = 1

Using the original taxi ndarray, calculate how many trips had JFK Airport as their destination:
1. Use boolean indexing to select only the rows where the dropoff_location_code column (column index 6) has a value that corresponds to JFK. Assign the result to jfk.
2. Calculate how many rows are in the new jfk array and assign the result to jfk_count.
3. Calculate how many trips from taxi had Laguardia Airport as their destination:
4. Use boolean indexing to select only the rows where the dropoff_location_code column (column index 6) has a value that corresponds to Laguardia. Assign the result to laguardia.
5. Calculate how many rows are in the new laguardia array. Assign the result to laguardia_count.
6. Calculate how many trips from taxi had Newark Airport as their destination:
7. Select only the rows where the dropoff_location_code column has a value that corresponds to Newark, and assign the result to newark.
8. Calculate how many rows are in the new newark array and assign the result to newark_count.
9. After you have run your code, inspect the values for jfk_count, laguardia_count, and newark_count and see which airport has the most dropoffs.


In [85]:
jfk = taxi[taxi[:,6] == 2]
laguardia = taxi[taxi[:,6] == 3]
newark = taxi[taxi[:,6] == 5]

In [87]:
jfk_count = jfk.shape[0]
laguardia_count = laguardia.shape[0]
newark_count = newark.shape[0]
print(jfk_count)
print(laguardia_count)
print(newark_count)

11832
16602
63


The trip_mph ndarray has been provided for you.

1. Create a new ndarray, cleaned_taxi, containing only rows for which the values of trip_mph are less than 100.
2. Calculate the mean of the trip_distance column of cleaned_taxi. Assign the result to mean_distance.
3. Calculate the mean of the trip_length column of cleaned_taxi. Assign the result to mean_length.
4. Calculate the mean of the total_amount column of cleaned_taxi. Assign the result to mean_total_amount.



In [93]:
cleaned_taxi = taxi[trip_mph < 100]
mean_distance = cleaned_taxi[:,7].mean()
mean_length = cleaned_taxi[:,8].mean()
mean_total_amount = cleaned_taxi[:,13].mean()