### Introduction to Ndarrays

In [1]:
import numpy as np

In [4]:
data_ndarry = np.array([5,10,15,20])
print(data_ndarry)

[ 5 10 15 20]


In [3]:
type(data_ndarry)

numpy.ndarray

In [6]:
import csv
f = open("nyc_taxis.csv","r")
taxi_list = list(csv.reader(f))
taxi_list = taxi_list[1:]


In [7]:
converted_taxi_list = []
for row in taxi_list:
    converted_row = []
    for item in row:
        converted_row.append(float(item))
    converted_taxi_list.append(converted_row)

In [8]:
data_ndarray = np.array(converted_taxi_list)
taxi = np.array(converted_taxi_list)

### Array Shape

Assign the shape of taxi to taxi_shape.

Print the result

In [12]:
taxi_shape = taxi.shape
print(taxi_shape)

(89560, 15)


### Selecting and Slicing Rows and Items 

From the taxi ndarray:

1. Select the row at index 0. Assign it to row_0.
2. Select every column for the rows at indexes 391 to 500 inclusive. Assign them to rows_391_to_500.
3. Select the item at row index 21 and column index 5. Assign it to row_21_column_5.


In [13]:
row_0 = taxi[0]

In [14]:
rows_391_to_500 = taxi[391:501]

In [15]:
row_21_column_5 = taxi[21,5]

### Selecting Columns and Custom Slicing

From the taxi ndarray:

1. Select every row for the columns at indexes 1, 4, and 7. Assign them to columns_1_4_7.
2. Select the columns at indexes 5 to 8 inclusive for the row at index 99. Assign them to row_99_columns_5_to_8.
3. Select the rows at indexes 100 to 200 inclusive for the column at index 14. Assign them to rows_100_to_200_column_14.

In [20]:
column_1_4_7 = taxi[:,[1,4,7]]

In [22]:
row_99_columns_5_to_8 = taxi[99,5:9]

In [24]:
row_100_to_200_column_14 = taxi[100:201,14]

### Vector Maths

1. Use vector addition to add fare_amount and fees_amount. Assign the result to fare_and_fees.
2. After you have run your code, use the variable inspector below the code box to inspect the variables.


In [26]:
fare_amount = taxi[:,9]
fees_amount = taxi[:,10]
fare_and_fees = taxi[:,9] + taxi[:,10]  

1. Use vector division to divide trip_distance_miles by trip_length_hours. Assign the result to trip_mph.
2. After you have run your code, use the variable inspector below the code box to inspect the contents of the new trip_mph variable.


In [27]:
trip_distance = taxi[:,7]
trip_length_seconds = taxi[:,8]
trip_length_hours = trip_length_seconds / 3600

In [28]:
trip_length_hours 

array([0.56583333, 0.42222222, 0.40611111, ..., 0.78388889, 0.30083333,
       0.47527778])

In [29]:
trip_distance_miles = taxi[:,7]

In [30]:
trip_mph = trip_distance_miles / trip_length_hours

In [31]:
trip_mph

array([37.11340206, 38.58157895, 31.27222982, ..., 22.29907867,
       42.41551247, 36.90473407])

### Calculating Statistics For 1D array

1. Use the ndarray.max() method to calculate the maximum value of trip_mph. Assign the result to mph_max.
2. Use the ndarray.mean() method to calculate the average value of trip_mph. Assign the result to mph_mean.

In [33]:
mph_min = trip_mph.min()
mph_max = trip_mph.max()
mph_mean = trip_mph.mean()

We've already assigned the first five rows of taxi to taxi_first_five and the first four columns in the table above to fare_components.

In [35]:
taxi_first_five = taxi[:5]
fare_component = taxi[:,9:13]

### Calculating Statistics For 2D array

Check that the sum of each row in fare_components equals the value in the total_amount column.

1. Use the ndarray.sum() method to calculate the sum of each row in fare_components. 
2. Assign the result to fare_sums.
3. Extract the 14th column in taxi_first_five. Assign to fare_totals.
4. Print fare_totals and fare_sums.


In [36]:
fare_sums = fare_component.sum(axis = 1)

In [38]:
fare_totals = taxi[:5,13]